version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies
      - poetry install --only main,docs

sphinx:
  configuration: docs/conf.py
